# Generated by Django 4.0.1 on 2022-12-18 20:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TipoMascota',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombreTipo', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emailUsuario', models.CharField(max_length=100)),
                ('nombreUsuario', models.CharField(max_length=15)),
                ('contrasena', models.CharField(max_length=80)),
                ('fechaCreacion', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Mascota',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombreMascota', models.CharField(max_length=20)),
                ('nivelMascota', models.IntegerField()),
                ('vidaMascota', models.IntegerField()),
                ('cuidadoMascota', models.IntegerField()),
                ('felicidadMascota', models.IntegerField()),
                ('fechaCreacion', models.DateTimeField(auto_now_add=True)),
                ('idUsuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='master.usuario')),
                ('tipoMascota', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='master.tipomascota')),
            ],
        ),
    ]
